/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rmowlana.avroschemaandregistry.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Inventory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8046714404289956016L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Inventory\",\"namespace\":\"com.rmowlana.avroschemaandregistry.dto\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"InventoryStatus\",\"symbols\":[\"IN_STOCK\",\"OUT_OF_STOCK\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Inventory> ENCODER =
      new BinaryMessageEncoder<Inventory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Inventory> DECODER =
      new BinaryMessageDecoder<Inventory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Inventory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Inventory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Inventory>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Inventory to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Inventory from a ByteBuffer. */
  public static Inventory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence orderId;
  @Deprecated public java.lang.CharSequence productId;
  @Deprecated public com.rmowlana.avroschemaandregistry.dto.InventoryStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Inventory() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param productId The new value for productId
   * @param status The new value for status
   */
  public Inventory(java.lang.CharSequence orderId, java.lang.CharSequence productId, com.rmowlana.avroschemaandregistry.dto.InventoryStatus status) {
    this.orderId = orderId;
    this.productId = productId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return productId;
    case 2: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: productId = (java.lang.CharSequence)value$; break;
    case 2: status = (com.rmowlana.avroschemaandregistry.dto.InventoryStatus)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.CharSequence getProductId() {
    return productId;
  }

  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.rmowlana.avroschemaandregistry.dto.InventoryStatus getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.rmowlana.avroschemaandregistry.dto.InventoryStatus value) {
    this.status = value;
  }

  /**
   * Creates a new Inventory RecordBuilder.
   * @return A new Inventory RecordBuilder
   */
  public static com.rmowlana.avroschemaandregistry.dto.Inventory.Builder newBuilder() {
    return new com.rmowlana.avroschemaandregistry.dto.Inventory.Builder();
  }

  /**
   * Creates a new Inventory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Inventory RecordBuilder
   */
  public static com.rmowlana.avroschemaandregistry.dto.Inventory.Builder newBuilder(com.rmowlana.avroschemaandregistry.dto.Inventory.Builder other) {
    return new com.rmowlana.avroschemaandregistry.dto.Inventory.Builder(other);
  }

  /**
   * Creates a new Inventory RecordBuilder by copying an existing Inventory instance.
   * @param other The existing instance to copy.
   * @return A new Inventory RecordBuilder
   */
  public static com.rmowlana.avroschemaandregistry.dto.Inventory.Builder newBuilder(com.rmowlana.avroschemaandregistry.dto.Inventory other) {
    return new com.rmowlana.avroschemaandregistry.dto.Inventory.Builder(other);
  }

  /**
   * RecordBuilder for Inventory instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Inventory>
    implements org.apache.avro.data.RecordBuilder<Inventory> {

    private java.lang.CharSequence orderId;
    private java.lang.CharSequence productId;
    private com.rmowlana.avroschemaandregistry.dto.InventoryStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.rmowlana.avroschemaandregistry.dto.Inventory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Inventory instance
     * @param other The existing instance to copy.
     */
    private Builder(com.rmowlana.avroschemaandregistry.dto.Inventory other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.status)) {
        this.status = data().deepCopy(fields()[2].schema(), other.status);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Inventory.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Inventory.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductId() {
      return productId;
    }

    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Inventory.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Inventory.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.rmowlana.avroschemaandregistry.dto.InventoryStatus getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Inventory.Builder setStatus(com.rmowlana.avroschemaandregistry.dto.InventoryStatus value) {
      validate(fields()[2], value);
      this.status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Inventory.Builder clearStatus() {
      status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Inventory build() {
      try {
        Inventory record = new Inventory();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.status = fieldSetFlags()[2] ? this.status : (com.rmowlana.avroschemaandregistry.dto.InventoryStatus) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Inventory>
    WRITER$ = (org.apache.avro.io.DatumWriter<Inventory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Inventory>
    READER$ = (org.apache.avro.io.DatumReader<Inventory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
