/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rmowlana.avroschemaandregistry.dto;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum InventoryStatus {
  IN_STOCK, OUT_OF_STOCK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InventoryStatus\",\"namespace\":\"com.rmowlana.avroschemaandregistry.dto\",\"symbols\":[\"IN_STOCK\",\"OUT_OF_STOCK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
