/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rmowlana.avroschemaandregistry.dto;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum KitchenStatus {
  PREPARING, READY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"KitchenStatus\",\"namespace\":\"com.rmowlana.avroschemaandregistry.dto\",\"symbols\":[\"PREPARING\",\"READY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
