/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rmowlana.avroschemaandregistry.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Kitchen extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3649726749888602611L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Kitchen\",\"namespace\":\"com.rmowlana.avroschemaandregistry.dto\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"KitchenStatus\",\"symbols\":[\"PREPARING\",\"READY\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Kitchen> ENCODER =
      new BinaryMessageEncoder<Kitchen>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Kitchen> DECODER =
      new BinaryMessageDecoder<Kitchen>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Kitchen> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Kitchen> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Kitchen>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Kitchen to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Kitchen from a ByteBuffer. */
  public static Kitchen fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence orderId;
  @Deprecated public com.rmowlana.avroschemaandregistry.dto.KitchenStatus status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Kitchen() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param status The new value for status
   */
  public Kitchen(java.lang.CharSequence orderId, com.rmowlana.avroschemaandregistry.dto.KitchenStatus status) {
    this.orderId = orderId;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: status = (com.rmowlana.avroschemaandregistry.dto.KitchenStatus)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.rmowlana.avroschemaandregistry.dto.KitchenStatus getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.rmowlana.avroschemaandregistry.dto.KitchenStatus value) {
    this.status = value;
  }

  /**
   * Creates a new Kitchen RecordBuilder.
   * @return A new Kitchen RecordBuilder
   */
  public static com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder newBuilder() {
    return new com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder();
  }

  /**
   * Creates a new Kitchen RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Kitchen RecordBuilder
   */
  public static com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder newBuilder(com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder other) {
    return new com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder(other);
  }

  /**
   * Creates a new Kitchen RecordBuilder by copying an existing Kitchen instance.
   * @param other The existing instance to copy.
   * @return A new Kitchen RecordBuilder
   */
  public static com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder newBuilder(com.rmowlana.avroschemaandregistry.dto.Kitchen other) {
    return new com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder(other);
  }

  /**
   * RecordBuilder for Kitchen instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Kitchen>
    implements org.apache.avro.data.RecordBuilder<Kitchen> {

    private java.lang.CharSequence orderId;
    private com.rmowlana.avroschemaandregistry.dto.KitchenStatus status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Kitchen instance
     * @param other The existing instance to copy.
     */
    private Builder(com.rmowlana.avroschemaandregistry.dto.Kitchen other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.status)) {
        this.status = data().deepCopy(fields()[1].schema(), other.status);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.rmowlana.avroschemaandregistry.dto.KitchenStatus getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder setStatus(com.rmowlana.avroschemaandregistry.dto.KitchenStatus value) {
      validate(fields()[1], value);
      this.status = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.rmowlana.avroschemaandregistry.dto.Kitchen.Builder clearStatus() {
      status = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Kitchen build() {
      try {
        Kitchen record = new Kitchen();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.status = fieldSetFlags()[1] ? this.status : (com.rmowlana.avroschemaandregistry.dto.KitchenStatus) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Kitchen>
    WRITER$ = (org.apache.avro.io.DatumWriter<Kitchen>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Kitchen>
    READER$ = (org.apache.avro.io.DatumReader<Kitchen>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
