/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rmowlana.avroschemaandregistry.dto;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PaymentStatus {
  PAYMENT_SUCCESS, PAYMENT_FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"namespace\":\"com.rmowlana.avroschemaandregistry.dto\",\"symbols\":[\"PAYMENT_SUCCESS\",\"PAYMENT_FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
